name: Build and Publish Docker Image

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nutrilife-backend:nightly .
          docker tag ${{ secrets.DOCKER_USERNAME }}/nutrilife-backend:nightly ${{ secrets.DOCKER_USERNAME }}/nutrilife-backend:${{ github.sha }}

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nutrilife-backend:nightly
          docker push ${{ secrets.DOCKER_USERNAME }}/nutrilife-backend:${{ github.sha }}
