name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          cd apps/server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nutrilife-backend:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/nutrilife-backend:latest ${{ secrets.DOCKER_USERNAME }}/nutrilife-backend:${{ github.sha }}

      # Push the Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nutrilife-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/nutrilife-backend:${{ github.sha }}
